### PR TITLE
Update design

### PR DESCRIPTION
**Pull request by gela-d**
---

Showcase is [available](http://bem.github.io/reports/6051/showcase/showcase.html)

Report is [available](http://bem.github.io/reports/6051/gemini-report)

### CODE REVIEW

**Comment by dfilatov** [comment]
I've tried it out on nmaps. Excepting https://github.com/bem/bem-components/pull/1838/files#diff-6dce689358f9ff2e55d919fc1ad4ba16R8, everything looks good.

**Comment by tadatuta** [comment]
@dfilatov is it fine for you to override it back on project level?

**Comment by dfilatov** [comment]
@tadatuta I think it's a suitable solution.

**Comment by dfilatov** [comment]
But don't forget about some unsemantic modifiers like "black".

**Comment by gela-d** [comment]
@tadatuta This commit broke some controls. For example, 

We should look on this change carefully

**Comment by dfilatov** [comment]
@gela-d good catch. I see that it has different appearance in FF and Chrome. It should be fixed.

**Comment by dfilatov** [comment]
Is there any progress?

**Comment by gela-d** [comment]
> Is there any progress?

Yes, we trying to fix and understand a problem with `line-heigth` form page. There is some problems with it.

**Comment by gela-d** [comment]
Close via #1853

**Pull request closed without merging**
