### PR TITLE
Add jsdoc for menu

### PR DESCRIPTION
**Pull request by apsavin**

### CODE REVIEW

**Comment by sipayRT** [comment]
@apsavin all types should be written with a capital letter. Also, check, pls, codestyle - you have an extra spaces in code - https://travis-ci.org/bem/bem-components/jobs/55144579

**Comment by apsavin** [comment]
@sipayRT done.
It's strange, I've succesfully done `npm run lint` before push, but travis still failed.

**Comment by tadatuta** [comment]
@apsavin travis failed on gemini tests. looks like Sauce Labs answers for too long.
restarted tests, let's see if it's a temporary issue...

**Comment by apsavin** [comment]
Yep, I'm sure that jsdoc can't break gemini tests)

**Comment by sipayRT** [comment]
@tadatuta because of broken firefox-v30 in Sauce Labs (Error: Cannot launch browser firefox-v30)

**Comment by sipayRT** [comment]
@apsavin we have some problems with SauceLabs key. So your changes was merged in the another [PR](https://github.com/bem/bem-components/pull/1440).

**Pull request closed without merging**
