### PR TITLE
Add select.setOptions method to dynamic update items #1100

### LINKED ISSUE #1100: select: allow dynamic update items

### PR DESCRIPTION
**Pull request by slonoed**
This resolves #1100

### CODE REVIEW

**Comment by aristov** [comment]
I run command `enb make specs desktop.specs/select` and get: `Error: Module "select": can't resolve dependence "menu"`
Addition `menu` block to `deps`-file resolves this problem.

**Comment by slonoed** [comment]
@aristov 
`npm run gemini`
works well localy, but fail in travis. Can you check and merge PR?

**Comment by aristov** [comment]
cc @veged, @dfilatov

**Comment by qfox** [comment]
Do we need `getOptions` method? It uses `menu.ptp.getItems`. Are you sure about naming?

**Comment by slonoed** [comment]
@zxqfox, `.getOptions` - bad idea. Only info than select should return - is selected values.

**Comment by qfox** [comment]
@SLonoed yeah, but that's strange to have `setOptions` without getter. Do you thought about appending some additional options to select? Anyway, it was just a suggestion.

**Comment by slonoed** [comment]
@zxqfox, maybe it about naming. `.updateOptions` can be more consistent.

**Comment by narqo** [comment]
Hey, @SLonoed thanks for pr and sorry for delay.

After a (long) discussion \w @veged and @dfilatov we decided that re-rendering the whole select is much better (and much universal) solution for such cases. At least on the current API state. Currently `updateOptions` doesn't have any particular benefits. But it brings the requirement of embedding BEMHTML templates inside client JS, as well as additional nested element.

Exact problem could be solve with such API enhancements on the project's level.

**Pull request closed without merging**
