### PR TITLE
checkbox, checkbox-group: improve JAWS readability

### LINKED ISSUE #1492: checkbox: improve JAWS readability
JAWS should read
- [x] `checkbox` as "checkbox not checked"
- [x] `checkbox_checked` as "checkbox checked"
- [x] `checkbox_disabled` as "checkbox unavailable"
- [x] `checkbox_type_button` as "toggle button"
- [x] `checkbox_type_button` + `_checked` as "toggle button pressed"
- [x] `checkbox_type_button` + `_disabled` as "toggle button unavailable"
- [x] `text` field
- [x] `title` field

Check and fix divergencies.

### PR DESCRIPTION
**Pull request by sipayRT**
Closes #1492 #1521

### CODE REVIEW

**Comment by sipayRT** [comment]
@aristov this branch was rebased. After button's review this code was totally remade in more easier way. Need your review

**Comment by aristov** [comment]
JAWS reads `text` field of `checkbox` (without `_type_button`) twice when arrow-key navigation is used. Try to use `span` with `role="presentation"` or `aria-hidden="true"` to wrap text and hide it from JAWS.

**Comment by sipayRT** [comment]
@aristov 

> JAWS reads text field of checkbox (without _type_button) twice

I thought that it's norman behavior. Added elem `__text` with 'aria-hidden' attribute. Plz, check it

**Comment by aristov** [comment]
LGTM

**Pull request merged**
