### PR TITLE
Remove symlinks

### LINKED ISSUE #1200: Symlinks on Windows
На винде падает сборка стайлуса из-за симлинок.

По логу ошибки там очевидно,  что stylus рассматривает симлинку как обычный файл и не подменяет контент по пути, а просто читает его (строка, которая представляет собой путь) и конечно же не может скомпилировать.

### PR DESCRIPTION
**Pull request by eGavr**
closes #1200

### CODE REVIEW

**Comment by tadatuta** [comment]
update with css include instead

**Comment by tadatuta** [comment]
after investigation in https://github.com/bem/bem-components/pull/1410 decided to get back to copypaste solution as otherwise we must hardcode relative urls to **built** files.

**Comment by narqo** [comment]
Should it be closed in favour of #1410? It seems that these two prs are about the same things.

**Comment by aristov** [comment]
Close in favour of #1410

**Pull request closed without merging**
