### PR TITLE
Split block's examples into examples and tests

### LINKED ISSUE #278: Распилить примеры блоков на examples и tests
Большую часть (все?) примеров блоков (`<block>.examples`) следует унести в `<block>.tests` поскольку они служат больше для тестирования функционала блока, чем для демонстрации блока потенциальному пользователю.

Логика распиливания на примеры/тесты должна быть следующая:

— если пример нужен разработчику/тестировщику блока для отладки кода — это **тест**. Его следует унести в `<block>.tests`
— если пример демонстрирует функциональность блока и потенциально должен показывать на сайте-витрине — это пример. Оставляем в `<block>.examples`

### PR DESCRIPTION
**Pull request by narqo**
Closes #278 

\cc @mishanga @veged

### CODE REVIEW

**Comment by narqo** [comment]
There is an error in mocha's CSS, so `roole` compilation fails. Will fix in narqo/bem-pr#67

**Comment by veged** [comment]
so we need to wait narqo/bem-pr#67 and bump version? can you do it in this PR?

**Comment by narqo** [comment]
@veged nope, bem-pr was fixed already, so code here is already ok ;) Waiting for comments/notes/etc (are there any @mishanga ?) and could merge it

**Comment by mishanga** [comment]
@narqo I don't understand anything here :) Merge it.

**Pull request merged**
