### PR TITLE
travis showcase publisher

### PR DESCRIPTION
**Pull request by tadatuta**
---

Showcase is [available](http://bem.github.io/reports/5748/showcase/showcase.html)

### CODE REVIEW

**Comment by narqo** [comment]
@tadatuta what is going on here?

**Comment by tadatuta** [comment]
publish link to PR remaining, going to finish it when get some time

**Comment by qfox** [comment]
@tadatuta I'm dropped the assignee lock. If you'll find some time — just assignee to yourself ;-)

**Comment by tadatuta** [comment]
Closing if favor of https://github.com/bem/bem-components/pull/1329

**Pull request merged**
