### PR TITLE
menu: Do not add tabindex attribute if disabled mod was set before init

### LINKED ISSUE #407: menu: Do not add "tabindex" attribute if "disabled" mod was set before init

### PR DESCRIPTION
**Pull request by narqo**
closes #407

### CODE REVIEW

**Comment by Guria** [comment]
What was a reason to made this change? It causes `menu` block unable to work as expected if it appears disabled initially. Control will not be able to get `tabIndex` attribute on mod `disabled` removed anymore. So it will be treated as unfocusable.
//cc @tadatuta 
I ask to revert this change. As `control` descendant `menu` block will store tabIndex in instance as `this._tabIndex` and remove attribute on domNode once block is inited.

**Comment by tadatuta** [comment]
cc @narqo

**Comment by qfox** [comment]
@Guria :+1:

**Comment by narqo** [comment]
We can't just revert these changes. The problem is that `menu` should not be "focusable" while it is disabled. But: 
- at the time such initially disabled block would get DOM-focus, it will be initialized;
- we would get indeterminate state: block is in the focus state, but there is no `_focused` modifier.

These problems are fixed in native "focusable" elements, with `disable` attribute. Could you open a separate issue about initially disabled `menu` – we would think about the right solution.

**Comment by Guria** [comment]
@narqo Ok, i will open an issue.
Is this problem just about menu, or other blocks that use tabIndex also affected? See #1190 for reference.
Also, IMO, a short moment when block in indeterminate state is better then block that doesn't work.

**Comment by narqo** [comment]
> Is this problem just about menu, or other blocks that use tabIndex also affected?

I think, currently the problem is only with `menu`. But will consider this case in other blocks with #1206

**Pull request merged**
