### PR TITLE
Updated build infrastructure

### LINKED ISSUE #1293: Update build infrastructure
1. Update npm deps
2. Review build config

### PR DESCRIPTION
**Pull request by blond**
Resolved #1293

### CODE REVIEW

**Comment by sipayRT** [comment]
It seems that modifier's js-code was missed in the dist-file. For example, in `dist/desktop/desktop.browser.js` I can't find code about `input_has-clear` - https://github.com/bem/bem-components/blob/v2/common.blocks/input/_has-clear/input_has-clear.js

**Comment by blond** [comment]
@sipayRT, https://github.com/enb-bem/enb-bem-techs/issues/103.

**Comment by sipayRT** [comment]
@andrewblond works fine now

**Pull request merged**
