### PR TITLE
menu: After disabled state tabindex has not been set

### LINKED ISSUE #1767: menu: After disabled state tabindex has not been set
If I have menu with `disabled` mod, and then make `menu.delMod('disabled')` tabindex has not been set.
In template we have this construction https://github.com/bem/bem-components/blob/v2/common.blocks/menu/menu.bemhtml#L45-L47.

### PR DESCRIPTION
**Pull request by narqo**
fix #1767

/cc @dfilatov

---

Showcase is [available](http://bem.github.io/reports/5841/showcase/showcase.html)

### CODE REVIEW

**Comment by tadatuta** [comment]
tmpl specs should be updated with this PR

**Comment by narqo** [comment]
@tadatuta I'm not sure I understand, what has happened with CI here. Could you explain, what's wrong with the specs?

**Comment by tadatuta** [comment]
@narqo build scrips were fixed in https://github.com/bem/bem-components/commit/a674f8475e86002b6e6e62e71d0338367a7cf02d

So I rebased the branch and added a fix for codestyle. Guess commits should be squashed before merge.

**Comment by narqo** [comment]
Amazing!

**Comment by tadatuta** [comment]
@narqo any reason not to merge?

**Comment by narqo** [comment]
It seems that tests for dist are not stable. But after I've restart the build everything looks fine.

**Pull request merged**
