### PR TITLE
button: collapsed without given specified text (close #887)

### LINKED ISSUE #887: button: collapsed without specified text

### PR DESCRIPTION
**Pull request by dfilatov**
cc @mishanga

### CODE REVIEW

**Comment by mishanga** [comment]
It can be fixed by CSS only:

``` css
.button_theme_normal .button__text:empty:before
{
    content: '\00a0';
}
```

**Comment by dfilatov** [comment]
@mishanga Does it actually depend on `_theme_normal`? It's not about style. Can I put this code to `button__text.styl`?

**Comment by mishanga** [comment]
@dfilatov yep, it really does. There are several ways to fix this bug.

BTW, current bug is caused by this:
https://github.com/bem/bem-components/blob/906aeee5aad9eb2c938934ef205f126cfe6046d5/design/common.blocks/select/_theme/select_theme_normal.styl#L12-L15
AFAIR `.button__text { display: block }` is needed just for select_width_available.

**Comment by dfilatov** [comment]
@mishanga I've remade PR, please check

**Comment by mishanga** [comment]
:+1:

**Pull request merged**
