### PR TITLE
fix 'text-overflow:ellipsis' behaviour in chrome

### LINKED ISSUE #1382: .input_has_clear.input_type_search: inadequate `text-overflow: ellipsis` behaviour in chrome
``` js
{ 
  block : 'input',
  mods : { theme : 'islands', size : 'l', 'has-clear' : true, type : 'search' },
}
```

Start input long text in input. It will get ellipsised once getting to edge of control.
demo

### PR DESCRIPTION
**Pull request by sipayRT**
Closes #1382

### CODE REVIEW

**Comment by sipayRT** [comment]
@hcodes check pls

**Comment by sipayRT** [comment]
@Guria

**Comment by hcodes** [comment]
:ok:

**Comment by Guria** [comment]
please wait, I'll test today or tomorrow.

**Pull request merged**
