### PR TITLE
radio: Refactoring CSS (#179)

### LINKED ISSUE #179: radio: Refactoring CSS

### PR DESCRIPTION
**Pull request by mishanga**
WARNING! Based on checkbox refactoring, merge only after https://github.com/bem/bem-components/pull/223
Close #179

### CODE REVIEW

**Comment by mishanga** [comment]
@dfilatov 
Rebased, ready for review and merge.

**Comment by mishanga** [comment]
By the way: the second button in fourth row on screenshot is hovered.

**Comment by mishanga** [comment]
Can we think that #167 is also closing by this request?

**Comment by dfilatov** [comment]
Yes, we can

**Pull request merged**
