### PR TITLE
input: extend attributes support

### PR DESCRIPTION
**Pull request by alexbaumgertner**
Add `require` and `type` block's fields.
http://www.w3.org/TR/html/forms.html#the-input-element

### CODE REVIEW

**Comment by sipayRT** [comment]
@alexbaumgertner why don't you add it on your project level? I think, these attributes not so useful, so there is no sense to add them to API

**Comment by alexbaumgertner** [comment]
@sipayRT I already added.
I belive, its common case. By current `input` block you can **not** add **any** attribute to `<input>` DOM node.
I can keep only extend attributes, if you insist.
And I still think that `required`, is at least required. :)

**Comment by aristov** [comment]
@alexbaumgertner these HTML-attributes should be represented as modifiers of the block.

**Comment by alexbaumgertner** [comment]
@aristov I agree. I'll rewrite code :)

**Comment by aristov** [comment]
@alexbaumgertner don't forget about [declared browsers support](https://github.com/bem/bem-components#supported-browsers). When you make these modifiers, you create a public API. It must work in all supported browsers.

**Pull request closed without merging**
