### PR TITLE
Use keyboard__codes

### LINKED ISSUE #408: Use bem-core's keyboard__codes instead of private constants
Since bem-core 2.2.0 we have [keyboard__codes](https://github.com/bem/bem-core/blob/v2.2.0/common.blocks/keyboard/__codes/keyboard__codes.js) module to use where private constants are used now

### PR DESCRIPTION
**Pull request by narqo**
closes #408

cc @dfilatov

### CODE REVIEW

**Comment by dfilatov** [comment]
Spec "menu hover on items should react on up/down keys when focused" has failed.

**Comment by narqo** [comment]
Crap, writing code during fly, without dependencies installed was not a good idea :) Fixed

**Comment by dfilatov** [comment]
But PR is still failed :)

**Comment by persidskiy** [comment]
It was a good idea to separate key codes into module. Looks really better now :+1:

**Comment by narqo** [comment]
> But PR is still failed :)

This time it was "Mocha timeout" bug :(

**Comment by dfilatov** [comment]
LGTM

**Pull request merged**
