### PR TITLE
islands theme: Implement new _focused* state for controls

### LINKED ISSUE #1109: Implement new _focused(-hard) state for controls
See o2 maillist for details

### PR DESCRIPTION
**Pull request by mishanga**
close #1109

### CODE REVIEW

**Comment by tadatuta** [comment]
screens update needed (http://bem.github.io/reports/3311/gemini-report/)

**Comment by dfilatov** [comment]
What about animation? )

**Comment by hcodes** [comment]
@mishanga 
Updated gemini screens + rebasing

**Comment by mishanga** [comment]
@hcodes thanks!

**Pull request merged**
