### PR TITLE
[WIP] select: improve JAWS readability

### LINKED ISSUE #1517: select: improve JAWS readability
JAWS should read
- [x] `select_focused` as "listbox"
- [x] `select_disabled` as "listbox unavailable"
- [ ] ~~`select_mode_check` as "extended select listbox"~~
- [ ] ~~`val` field as corresponding `options` list item's `text` field + "listbox item selected"~~
- [x] `text` field
- [x] position of selected option and total length of `options` list as "[position] of [length]"

Check and fix divergencies.

### PR DESCRIPTION
**Pull request by sipayRT**
Closes #1517

### CODE REVIEW

**Comment by sipayRT** [comment]
try to move all `aria-*` attributes to select and hide `__button` element

**Comment by sipayRT** [comment]
@aristov I moved all `aria` attributes to button and it looks much better now. Check it by JAWS pls

**Comment by sipayRT** [comment]
@aristov still waiting for your review

**Comment by aristov** [comment]
I will look it today.

**Comment by aristov** [comment]
I've checked result and found out that some points of original issue are not implemented.
Try this pure HTML with JAWS, to check proper result:

``` html
<div role="listbox" tabindex="0">
    <div role="option" id="123">block</div>
    <div role="option" id="234" aria-selected="true">element</div>
    <div role="option" id="345">modifier</div>
</div>
```

**Comment by aristov** [comment]
Redundant "has popup" and "collapsed" phrases should be removed.

**Comment by aristov** [comment]
Close in favour of #1663

**Pull request closed without merging**
