### PR TITLE
Add to deps.js dependence from i-bem

### LINKED ISSUE #762: Add to deps.js dependence from i-bem

### PR DESCRIPTION
**Pull request by gela-d**
Close #762

### CODE REVIEW

**Comment by gela-d** [comment]
cc @dfilatov @tadatuta

**Comment by dfilatov** [comment]
@gela-d Is it for BEMHTML-templates?

**Comment by gela-d** [comment]
@dfilatov yes, and we have some problems, when write tests on templates

**Comment by dfilatov** [comment]
@gela-d ok

**Pull request merged**
