### PR TITLE
Update jscs, fix codestyle. Closes #745

### LINKED ISSUE #745: Update jscs, fix codestyle

### PR DESCRIPTION
**Pull request by tadatuta**
cc @dfilatov

### CODE REVIEW

**Comment by mishanga** [comment]
:+1:

**Comment by mishanga** [comment]
Something went wrong:

```
$ git commit
Error: Syntax error at common.blocks/icon/icon.styl: Line 1: Unexpected token .
    at StringChecker.checkString (/Users/mishanga/bem-components/node_modules/jscs/lib/string-checker.js:221:19)
    at /Users/mishanga/bem-components/node_modules/jscs/lib/checker.js:48:26
    at Array.0 (/Users/mishanga/bem-components/node_modules/jscs/node_modules/vow/lib/vow.js:555:56)
    at Object.callFns [as _onImmediate] (/Users/mishanga/bem-components/node_modules/jscs/node_modules/vow/lib/vow.js:1148:35)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by tadatuta** [comment]
@mishanga it was bad idea to leave soft dependency for `jscs` in `package.json`, now if file isn't explicitly added to `exclude` section it's gonna be checked. will fix the version.

**Comment by tadatuta** [comment]
done: https://github.com/bem/bem-components/commit/84269fed566ba22a0a144a67ff9b9e2cb4f1c154

**Pull request merged**
