### PR TITLE
select should have deps icon

### PR DESCRIPTION
**Pull request by voischev**
Block `icon` in template inside https://github.com/bem/bem-components/blob/v2/common.blocks/select/__button/select__button.bemhtml#L19

### CODE REVIEW

**Comment by tadatuta** [comment]
@voischev 
Dependency is declared on design level: https://github.com/bem/bem-components/blob/v2/design/common.blocks/select/_theme/select_theme_islands.deps.js#L8

Are you sure it's really needed without design anyways?

**Comment by voischev** [comment]
What about the right tag... & icon template in common.blocks?

**Comment by voischev** [comment]
Why is there a deps on `button`, there is no deps on `icon`. Although in the template, it is also present too.

**Comment by narqo** [comment]
Ok, looks fine. Thanks.

**Pull request merged**
