### PR TITLE
popup: add specs for calcPossibleDrawingParams

### PR DESCRIPTION
**Pull request by qfox**
Continue of #1194

### CODE REVIEW

**Comment by veged** [comment]
is it still WIP?

**Comment by qfox** [comment]
@veged I'm borrowed into another problem atm. Can you tackle this?

**Comment by narqo** [comment]
@zxqfox Can you describe the state of the pr? Is everything is done and we need to review? Or do we need to do something more here and what exactly?

**Comment by qfox** [comment]
@narqo I don't know what I can do here. I don't know code as well as I should to finish it. But I remember that @veged said in PR that it's like something what we need.

**Comment by deeonis** [comment]
@zxqfox what are you going to do with this pr?

**Comment by qfox** [comment]
@deeonis Waiting for suggestions...

**Comment by narqo** [comment]
@zxqfox finally! We've reviewed it and it looks fine. Could you squash commits here, so we can merge it?

**Comment by qfox** [comment]
@narqo Thanks ;-) I'll do it soon.

**Comment by narqo** [comment]
@zxqfox you have some code-style problems here

**Comment by qfox** [comment]
@narqo yup, fixing, sorry.

**Comment by qfox** [comment]
@narqo Okay. Some errors with jquery-static, all other is fine.

**Comment by narqo** [comment]
Yep! It looks like it's a problem after HSTS was turned on on `yastatic.net`. Will try to investigate it.

**Comment by narqo** [comment]
Ok, "pr" build passed. Looks good, thanks

**Pull request merged**
