### PR TITLE
icon: add support for inline svg/img

### LINKED ISSUE #523: icon: add support for inline svg/img
``` html
<span class="icon">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22"><path d="M21.5,13.5 L21.5,14.5 L11.5,21 L10.5,21 L0.5,14.5 L0.5,13.5 L3,12 L3.5,12.5 L1.5,14 L10.5,20 L11.5,20 L20.5,14 L18.5,12.5 L19,12 L21.5,13.5 Z"></path><path d="M11.5,15 L21.5,8.5 L21.5,7.5 L11.5,1 L10.5,1 L0.5,7.5 L0.5,8.5 L10.5,15 L10.5,15 Z M10.5,2 L11.5,2 L20.5,8 L11.5,14 L10.5,14 L1.5,8 Z"></path></svg>
</span>
```

``` javascript
{
    block : 'icon',
    content : '<svg ... />'
}
```

### PR DESCRIPTION
**Pull request by mishanga**
Close #523

### CODE REVIEW

**Comment by mishanga** [comment]
@dfilatov

**Comment by mishanga** [comment]
Implemented cool solution from @boronchiev

**Comment by dfilatov** [comment]
@mishanga It's an old well-known trick. Does it work in all browsers we support?

**Comment by mishanga** [comment]
@dfilatov yep, it was tested in IE 9+, Chrome, FF, Opera 12, iOS Safari.

**Pull request merged**
