### PR TITLE
button: remove textMaxWidth option

### LINKED ISSUE #1268: button: remove textMaxWidth

### PR DESCRIPTION
**Pull request by sipayRT**
Closes #1268

### CODE REVIEW

**Comment by sipayRT** [comment]
@dfilatov

**Comment by dfilatov** [comment]
Let's get rid of corresponding option in `select`. It depends on `button`.

**Comment by sipayRT** [comment]
I found [HTML](https://github.com/bem/bem-components/blob/v2/common.blocks/select/select.tmpl-specs/30-control-val-json.html) for `tmpl-specs` that hasn't `bemjson` for test. In this commit it was deleted.

**Comment by dfilatov** [comment]
lgtm

**Comment by sipayRT** [comment]
agrrrrrr.... some errors in gemini
textarea
@hcodes have you seen this error before?

**Pull request merged**
