### PR TITLE
input: Too large carriage in Chrome & Safari

### LINKED ISSUE #563: input: Too large carriage in Chrome & Safari

### PR DESCRIPTION
**Pull request by gela-d**
Close #563

### CODE REVIEW

**Comment by mishanga** [comment]
Take a look on `normal` page.

Zoom 100%:


Zoom 175%:

**Comment by gela-d** [comment]
@mishanga Look, please, at  this commit - https://github.com/bem/bem-components/commit/2927758c0b8d6aa48eae49d4c9dbfc51d5c5bb45
I removed hack for IE9, but visually everything remains as it was before
Before:
ie9 old
After my commit:
ie9 new
In Fx:
norm browsers

**Comment by mishanga** [comment]
LGTM

**Comment by sipayRT** [comment]
+1

**Comment by mishanga** [comment]
squash & merge

**Comment by gela-d** [comment]
done

**Pull request merged**
