### PR TITLE
input_theme_normal: add text-overflow: ellipsis

### PR DESCRIPTION
**Pull request by dfilatov**
cc @mishanga @gela-d

### CODE REVIEW

**Comment by gela-d** [comment]
I don't like how `_type_password` looks.
And maybe we add 2px-padding-right to our inputs?

**Comment by dfilatov** [comment]
Might be add `text-overflow` only in case of `_has-clear` and not `_type_password`?

**Comment by gela-d** [comment]
Yes, it would solve both problems

**Comment by dfilatov** [comment]
But it makes me use hellish css-selector (

**Comment by sipayRT** [comment]
why do you think that `:not()` is so ugly?

**Comment by dfilatov** [comment]
What could be more ugly than `.input_theme_normal.input_has-clear:not(.input_type_password) .input__control`?

**Comment by gela-d** [comment]
If you dont' want use `:not`, we can add `ellipsis` for all our `input_has-clear`, but for `.input_type_password` write `text-overflow: clip`?

**Comment by mishanga** [comment]
@gela-d yep, it would be better.

**Comment by dfilatov** [comment]
@gela-d I've updated PR, please, check

**Comment by mishanga** [comment]
:shipit:

**Pull request merged**
