### PR TITLE
checkbox, radio: Sync prop to support jQuery form serialization #1768

### PR DESCRIPTION
**Pull request by tadatuta**
---

Showcase is [available](http://bem.github.io/reports/5807/showcase/showcase.html)

### CODE REVIEW

**Comment by tadatuta** [comment]
cc @dfilatov

**Comment by dfilatov** [comment]
Please, add more information. I don't understand what you mean by "subsequent checks".

**Comment by tadatuta** [comment]
@dfilatov  Way to reproduce on current `v2 HEAD`:
1. Check `checkbox_type_button` // everything is ok
2. Uncheck // still ok
2. Check again // since this moment form won't serialize this checkbox anymore

**Comment by narqo** [comment]
Could the issue be reproduced using API calls? If so, tests are strongly advisable as this looks like another degradation connected with a11y refactoring.

**Comment by tadatuta** [comment]
@narqo I added test, it fails with old code and passes with my changes, but I'm not sure about implementation, though. Please take a look.

**Comment by narqo** [comment]
As I can see from the [implementation of `$.serializeArray()`](https://github.com/jquery/jquery/blob/70526981916945dc4093e116a3de61b1777d4718/src/serialize.js#L108), we should have the same "issue" in `radio`, as it uses `attr/removeAttr` as well (one could check some other blocks, I don't remember all the details of our a11y refactoring).

Just to be noted: I believe the title of issue/pr should be change because it's about jQuery's implementation of it's serialiser or even about how jQuery deal with internal DOM properties.

It was obvious that `attr('checked')` and `removeAttr('checked')` don't do anything with internal DOM properties, but only deal with HTML attributes. Do we expect this DOM APIs to work? If yes, the test might be significantly simplified to something like this

``` js
checkbox.setMod('checked');
checkbox.elem('control')[0].checked.should.be.true;
```

**Comment by dfilatov** [comment]
@tadatuta Could you fix the same stuff in `radio` as well and simplify specs?

**Comment by tadatuta** [comment]
@dfilatov, sure, will do it today

**Pull request merged**
