### PR TITLE
Rename "normal" theme to "islands"

### LINKED ISSUE #1038: Rename "normal" theme to "islands"
Current `normal` theme has nothing "normal" in it's name, as well as in the way it looks. I propose the name `islands` as it sounds much clearer from the open source POV (at least we have http://islands.yandex.com as "a historical reasons to call it "islands")

### PR DESCRIPTION
**Pull request by narqo**
closes #1038

### CODE REVIEW

**Comment by arikon** [comment]
@narqo Нужно переименовать картинки для тестов `gemini`

**Comment by narqo** [comment]
It seems that the only problem now is with deps building with `enb` that is described in #1037

**Comment by narqo** [comment]
Done!
/cc @veged @tadatuta 

@dfilatov take a note ;)

**Comment by narqo** [comment]
Anyone?

**Comment by dfilatov** [comment]
@narqo I've taken the note )

**Comment by tadatuta** [comment]
lgtm

**Pull request merged**
